# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: '31 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node getTinfoil.js
    
    - uses: actions/checkout@master
    - name: Get Latest Release
      id: latest_version
      uses: abatilo/release-info-action@v1.3.0
      with:
        owner: kkkkyue
        repo: Tinfoil
    
    - name: Create Release
      run: |
        set -x
        assets=()
        s1=''
        s2=''
        for asset in ./*.zip; do
          assets+=("-a" "$asset")
          h1=${asset%]*}
          s1=${h1##*[}
          h2=${h1%]*}
          s2=${h2##*[}
        done
        for asset in ./*.nsp; do
          assets+=("-a" "$asset")
        done
        if [ ${{ steps.latest_version.outputs.latest_tag }} = "${s2}.${s1}" ]; then hub release delete "${s2}.${s1}"; fi
        hub release create "${assets[@]}" -m "Tinfoil ${s2}.${s1}" "${s2}.${s1}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
